// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiRiSGI.Models;

#nullable disable

namespace WebApiRiSGI.Migrations
{
    [DbContext(typeof(SgiContext))]
    partial class SgiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiRiSGI.Models.Activos", b =>
                {
                    b.Property<int>("ActivosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActivosID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivosId"));

                    b.Property<string>("ActivoPrincipal")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ActivoSecundario")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MarcaActivo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ModeloActivo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Serial")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("TipoActivo")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("ActivosId");

                    b.ToTable("Activos");
                });

            modelBuilder.Entity("WebApiRiSGI.Models.Areas", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AreaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("DepartamentoID");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("WebApiRiSGI.Models.Asignaciones", b =>
                {
                    b.Property<int>("AsigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsigId"));

                    b.Property<int>("ActivosId")
                        .HasColumnType("int")
                        .HasColumnName("ActivosID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("AsigId");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("WebApiRiSGI.Models.Departamentos", b =>
                {
                    b.Property<string>("Departamento1")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("Departamento");

                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepartamentoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartamentoId"));

                    b.Property<int>("LocalidadId")
                        .HasColumnType("int")
                        .HasColumnName("LocalidadID");

                    b.Property<int>("OrganoId")
                        .HasColumnType("int")
                        .HasColumnName("OrganoID");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("WebApiRiSGI.Models.Descargos", b =>
                {
                    b.Property<int>("DescargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DescargoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DescargoId"));

                    b.Property<int?>("ActivoId")
                        .HasColumnType("int")
                        .HasColumnName("ActivoID");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("AreaID");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int?>("LocalidadId")
                        .HasColumnType("int")
                        .HasColumnName("LocalidadID");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UsuarioRemitente")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("DescargoId");

                    b.ToTable("Descargos");
                });

            modelBuilder.Entity("WebApiRiSGI.Models.Localidades", b =>
                {
                    b.Property<string>("Localidad")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("LocalidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LocalidadID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalidadId"));

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("WebApiRiSGI.Models.Marcas", b =>
                {
                    b.Property<string>("Marca1")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("Marca");

                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MarcaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaId"));

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("WebApiRiSGI.Models.Modelos", b =>
                {
                    b.Property<int>("MarcaId")
                        .HasColumnType("int")
                        .HasColumnName("MarcaID");

                    b.Property<string>("Modelo1")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("Modelo");

                    b.Property<int>("ModeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModeloID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeloId"));

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("WebApiRiSGI.Models.Movimientos", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MovimientoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoId"));

                    b.Property<int>("ActivoId")
                        .HasColumnType("int")
                        .HasColumnName("ActivoID");

                    b.Property<int>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("AreaID");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("int")
                        .HasColumnName("LocalidadID");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UsuarioDestino")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UsuarioRemitente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("MovimientoId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("WebApiRiSGI.Models.Organos", b =>
                {
                    b.Property<string>("Organo1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Organo");

                    b.Property<int>("OrganoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrganoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganoId"));

                    b.ToTable("Organos");
                });

            modelBuilder.Entity("WebApiRiSGI.Models.Roles", b =>
                {
                    b.Property<int>("RoliD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoliD"));

                    b.Property<bool>("RolActivo")
                        .HasColumnType("bit");

                    b.Property<string>("RolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoliD");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WebApiRiSGI.Models.RolesUsuarios", b =>
                {
                    b.Property<int>("UserRoliD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoliD"));

                    b.Property<int>("RoliD")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoliD")
                        .HasName("PK_UserRoles");

                    b.ToTable("RolesUsuarios");
                });

            modelBuilder.Entity("WebApiRiSGI.Models.TipoActivo", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TipoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoId"));

                    b.Property<string>("TipoNombre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoNombre");

                    b.HasKey("TipoId");

                    b.ToTable("TipoActivos");
                });

            modelBuilder.Entity("WebApiRiSGI.Models.Usuarios", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("AreaID");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("UserPass")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.HasKey("UserId");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
